// <auto-generated />
using System.Collections.Generic;
using static VMUnityAutomation.Editor.MCPBuiltInRouteDescriptor;

[assembly: VMUnityAutomation.Editor.MCPBuiltInRouteProvider(
    typeof(VMUnityAutomation.Editor.Localization.MCPLocalizationRouteProvider))]

namespace VMUnityAutomation.Editor.Localization
{
    internal sealed class MCPLocalizationRouteProvider : IMCPBuiltInRouteProvider
    {
        private static readonly MCPBuiltInRouteDescriptor[] DescriptorArray =
        {
            CreateImmediate("localization/collections", arguments => MCPLocalizationCommands.ListCollections(arguments)),
            CreateImmediate("localization/create-collection", arguments => MCPLocalizationCommands.CreateCollection(arguments)),
            CreateImmediate("localization/create-locale", arguments => MCPLocalizationCommands.CreateLocale(arguments)),
            CreateImmediate("localization/entries", arguments => MCPLocalizationCommands.ListEntries(arguments)),
            CreateImmediate("localization/locales", arguments => MCPLocalizationCommands.ListLocales(arguments)),
            CreateImmediate("localization/remove-entry", arguments => MCPLocalizationCommands.RemoveEntry(arguments)),
            CreateImmediate("localization/remove-variable", arguments => MCPLocalizationCommands.RemoveVariable(arguments)),
            CreateImmediate("localization/set-selected-locale", arguments => MCPLocalizationCommands.SetSelectedLocale(arguments)),
            CreateImmediate("localization/settings", arguments => MCPLocalizationCommands.UpdateSettings(arguments)),
            CreateImmediate("localization/status", arguments => MCPLocalizationCommands.GetStatus()),
            CreateDeferred("localization/upsert-entry", MCPLocalizationCommands.UpsertEntriesDeferred),
            CreateImmediate("localization/upsert-variable", arguments => MCPLocalizationCommands.UpsertVariable(arguments)),
            CreateImmediate("localization/validate", arguments => MCPLocalizationCommands.Validate(arguments)),
            CreateImmediate("localization/variables", arguments => MCPLocalizationCommands.ListVariables(arguments)),
        };

        public IReadOnlyList<MCPBuiltInRouteDescriptor> Descriptors => DescriptorArray;

        public string AuditedRouteManifestSha256 =>
            MCPToolConfigurationPolicy.AuditedLocalizationRouteManifestSha256;
    }
}
