// <auto-generated />
using System.Collections.Generic;
using static VMUnityAutomation.Editor.VmAutomationBuiltInRouteDescriptor;

[assembly: VMUnityAutomation.Editor.VmAutomationBuiltInRouteProvider(
    typeof(VMUnityAutomation.Editor.Localization.VmAutomationLocalizationRouteProvider))]

namespace VMUnityAutomation.Editor.Localization
{
    internal sealed class VmAutomationLocalizationRouteProvider : IVmAutomationBuiltInRouteProvider
    {
        private static readonly VmAutomationBuiltInRouteDescriptor[] DescriptorArray =
        {
            CreateImmediate("localization/collections", arguments => VmAutomationLocalizationCommands.ListCollections(arguments)),
            CreateImmediate("localization/create-collection", arguments => VmAutomationLocalizationCommands.CreateCollection(arguments)),
            CreateImmediate("localization/create-locale", arguments => VmAutomationLocalizationCommands.CreateLocale(arguments)),
            CreateImmediate("localization/entries", arguments => VmAutomationLocalizationCommands.ListEntries(arguments)),
            CreateImmediate("localization/locales", arguments => VmAutomationLocalizationCommands.ListLocales(arguments)),
            CreateImmediate("localization/remove-entry", arguments => VmAutomationLocalizationCommands.RemoveEntry(arguments)),
            CreateImmediate("localization/remove-variable", arguments => VmAutomationLocalizationCommands.RemoveVariable(arguments)),
            CreateImmediate("localization/set-selected-locale", arguments => VmAutomationLocalizationCommands.SetSelectedLocale(arguments)),
            CreateImmediate("localization/settings", arguments => VmAutomationLocalizationCommands.UpdateSettings(arguments)),
            CreateImmediate("localization/status", arguments => VmAutomationLocalizationCommands.GetStatus()),
            CreateDeferred("localization/upsert-entry", VmAutomationLocalizationCommands.UpsertEntriesDeferred),
            CreateImmediate("localization/upsert-variable", arguments => VmAutomationLocalizationCommands.UpsertVariable(arguments)),
            CreateImmediate("localization/validate", arguments => VmAutomationLocalizationCommands.Validate(arguments)),
            CreateImmediate("localization/variables", arguments => VmAutomationLocalizationCommands.ListVariables(arguments)),
        };

        public IReadOnlyList<VmAutomationBuiltInRouteDescriptor> Descriptors => DescriptorArray;

        public string AuditedRouteManifestSha256 =>
            VmAutomationToolConfigurationPolicy.AuditedLocalizationRouteManifestSha256;
    }
}
